plugins {
    id 'com.android.library'
}

android {
    namespace 'opendoja.dexlib'
    compileSdk 34

    defaultConfig {
        minSdk 28
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    lint {
        abortOnError false
    }
}

dependencies {
    implementation 'net.lingala.zip4j:zip4j:2.11.5'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.compilerArgs += ['-Xmaxerrs', '10000']
}
